version: 2
jobs:
    tests-v8:
        docker:
            - image: circleci/node:8
            - image: redis
        steps:
            - checkout
            - run:
                name: Install dependencies
                command: npm install
            - run: 
                name: Linter
                command: npm run lint
            - run:
                name: Test
                command: npm test
    tests-v10:
        docker:
            - image: circleci/node:10
            - image: redis
        steps:
            - checkout
            - run:
                name: Install dependencies
                command: npm install
            - run: 
                name: Linter
                command: npm run lint
            - run:
                name: Test
                command: npm test
    application:
        docker:
            - image: circleci/node:10
        steps:
            - checkout
            - run:
                name: Install dependencies
                command: npm install
            - run:
                name: Run application
                command: npm start
workflows:
    version: 2
    build-deploy:
        jobs:
            - tests-v8
            - tests-v10
            - application
